import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from "next/image";

import bg from '../../public/images/bali.jpg';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body 
        // style={{
        //   backgroundImage: `url(${bg.src})`,
        //   objectFit: 'cover',
          
        // }}
      className={`${inter.className} relative`}>
        {children}
        
        <img
          src={"/images/bali.jpg"}
          alt="backoground-bali"
          className="fixed top-0 -z-10  left-0 w-screen h-screen object-cover"
        />
      </body>
    </html>
  );
}
